jobs:
  install_and_test:
    parameters:
      install-version:
        type: string
        default: "7.2"
      symfony-version:
        type: string
        default: "v5.2.99"
    docker:
      # Ubuntu 18.04 base image
      - image: 'cimg/base:2020.12-18.04'
    steps:
      - php/install-php:
          version: '<<parameters.install-version>>'
      # Minimal packages for symfony to run with xdebug
      - run: sudo apt install php<<parameters.install-version>>-xdebug php<<parameters.install-version>>-xml
      # Add xdebug.ini with xdebug.var_display_max_depth = -1
      - checkout
      - run: sudo cp ~/project/xdebug.ini /etc/php/<<parameters.install-version>>/mods-available/xdebug.ini
      - php/install-composer:
          install-version: 2.0.8
      - run: XDEBUG_MODE=off composer create-project symfony/website-skeleton:"<<parameters.symfony-version>>" symfony
      - run: mv symfony/* symfony/.??* .
      - run: rmdir symfony
      # Try to limit memory to 128M and timeout after 30s so that cache:clear crashes more quickly
      # console cache:clear is run after install with the composer.json settings
      - run: APP_ENV=dev APP_RUNTIME_ENV=dev timeout 15s php<<parameters.install-version>> -d memory_limit=128M bin/console cache:clear
orbs:
  php: circleci/php@1.1.0
version: 2.1

workflows:
  install:
    jobs:
      - install_and_test
      - install_and_test:
          install-version: "7.2"
          symfony-version: "5.2.x@dev"
            name: "php-<<parameters.install-version>> <<parameters.symfony-version>>"



