jobs:
  install_and_test:
    docker:
      # Ubuntu 18.04 base image
      - image: 'cimg/base:2020.12-18.04'
    steps:
      - php/install-php:
          version: '7.2'
      #- run: sudo apt-get update
      # Minimal packages for symfony to run with xdebug
      - run: sudo apt install php7.2-xdebug php7.2-xml
      # A list of all my installed packages
      #- run: sudo apt install php7.2-phpdbg php7.2-dev php7.2-fpm php7.2-gd php7.2-intl php7.2-mbstring php7.2-mysql php7.2-opcache php7.2-readline php7.2-sqlite3 php7.2-soap php7.2-xmlrpc php7.2-zip
      - checkout
      - php/install-composer:
          install-version: 2.0.8
      - run: sudo ln -s /usr/local/bin/composer /usr/bin/composer
#      - run: sudo ls -al /usr/bin/composer
#      - run: sudo ls -al /usr/local/bin/composer
#      - run: echo $PATH
#      - run: whereis composer
#      - run: which composer
#      - run: hash -r
#      - run: echo $PATH
#      - run: whereis composer
#      - run: which composer
#      - run: pwd
#      - run: ls -al
#      - run: ls -alR
#      - run: php -v
#      - run: php --ini
      - php/install-packages
      - run: composer require symfony/dependency-injection
      - run: composer require doctrine/doctrine-bundle
      - run: composer require --dev doctrine/doctrine-fixtures-bundle
      - run: php7.2 -d memory_limit=128M bin/console cache:clear
      #- run: composer validate
orbs:
  php: circleci/php@1.1.0
version: 2.1

workflows:
  install:
    jobs:
      - install_and_test



