jobs:
  install_and_test:
    docker:
      - image: 'cimg/base:2020.12-18.04'
    steps:
      - php/install-php:
          version: '7.2'
      - run: sudo apt-get update
      - run: sudo apt install php-xdebug

      - php/install-composer:
          install-version: 1.10.16
      - run: sudo ln -s /usr/local/bin/composer /usr/bin/composer
      - run: sudo ls -al /usr/bin/composer
      - run: sudo ls -al /usr/local/bin/composer
      - run: echo $PATH
      - run: whereis composer
      - run: which composer
      - run: hash -r
      - run: echo $PATH
      - run: whereis composer
      - run: which composer
      - checkout
      - php/install-packages:
          app-dir: ~/project/symfony
      - run: composer validate
orbs:
  php: circleci/php@1.1.0
version: 2.1

workflows:
  install:
    jobs:
      - install_and_test



