jobs:
  install_php:
    docker:
      - image: cimg/base:2020.12-18.04
    steps:
      - checkout
      - run: sudo apt-get update
      - php/install-php:
          version: '7.3'
  test_php:
    steps:
      - php/test:
          test-command: 'validate'
orbs:
  php: circleci/php@1.1.0
version: 2.1
workflows:
  install:
    jobs:
      - install_php
      - install_composer_packages
  test:
    jobs:
      - test_php
