jobs:
  install_php:
    docker:
      - image: 'cimg/base:2020.12-18.04'
    steps:
      - php/install-php:
          version: '7.2'
      - run: sudo apt-get update
      - run: sudo apt install php-xdebug
      - php/install-composer:
          install-version: 1.10.16
      - run: sudo ln -s /usr/local/bin/composer /usr/bin/composer
  test_php:
    docker:
      - image: 'cimg/base:2020.12-18.04'
    steps:
      - checkout
      - php/install-packages:
          app-dir: ~/project/symfony
      - run: /usr/local/bin/composer validate
orbs:
  php: circleci/php@1.1.0
version: 2.1

workflows:
  install:
    jobs:
      - install_php
      - test_php:
          requires:
            - install_php



