version: 2.1
orbs:
    php: circleci/php@1.1.0
jobs:
    build:
        docker:
            - image: cimg/base:2020.12-18.04
        steps:
            - checkout
            - run: sudo apt-get update
            - php/install-php:
                version: '7.3'
            - php/test
                test-command: 'validate'
workflows:
    install:
        jobs:
            - install_php
            - install_composer_packages
    test:
        jobs:
            - php/test
