jobs:
  install_and_test_72:
    docker:
      # Ubuntu 18.04 base image
      - image: 'cimg/base:2020.12-18.04'
    steps:
      - php/install-php:
          version: '7.2'
      # Minimal packages for symfony to run with xdebug
      - run: sudo apt install php7.2-xdebug php7.2-xml
      - checkout
      # Add xdebug.ini with xdebug.var_display_max_depth = -1
      - run: sudo cp ~/project/xdebug.ini /etc/php/7.2/mods-available/xdebug.ini
      - php/install-composer:
          install-version: 2.0.8
      # Try to limit memory to 128M and timeout after 30s so that cache:clear crashes more quickly
      # console cache:clear is run after install with the composer.json settings
      - run: timeout 30s php7.2 -d memory_limit=128M /usr/local/bin/composer install --no-interaction --prefer-dist
  install_and_test_73:
    docker:
      # Ubuntu 18.04 base image
      - image: 'cimg/base:2020.12-18.04'
    steps:
      - php/install-php:
          version: '7.3'
      # Minimal packages for symfony to run with xdebug
      - run: sudo apt install php7.3-xdebug php7.3-xml
      - checkout
      # Add xdebug.ini with xdebug.var_display_max_depth = -1
      - run: sudo cp ~/project/xdebug.ini /etc/php/7.3/mods-available/xdebug.ini
      - php/install-composer:
          install-version: 2.0.8
      # Try to limit memory to 128M and timeout after 30s so that cache:clear crashes more quickly
      # console cache:clear is run after install with the composer.json settings
      - run: timeout 30s php7.3 -d memory_limit=128M /usr/local/bin/composer install --no-interaction --prefer-dist
  install_and_test_74:
    docker:
      # Ubuntu 18.04 base image
      - image: 'cimg/base:2020.12-18.04'
    steps:
      - php/install-php:
          version: '7.4'
      # Minimal packages for symfony to run with xdebug
      - run: sudo apt install php7.4-xdebug php7.4-xml
      - checkout
      # Add xdebug.ini with xdebug.var_display_max_depth = -1
      - run: sudo cp ~/project/xdebug.ini /etc/php/7.4/mods-available/xdebug.ini
      - php/install-composer:
          install-version: 2.0.8
      # Try to limit memory to 128M and timeout after 30s so that cache:clear crashes more quickly
      # console cache:clear is run after install with the composer.json settings
      - run: timeout 30s php7.4 -d memory_limit=128M /usr/local/bin/composer install --no-interaction --prefer-dist
  install_and_test_80:
    docker:
      # Ubuntu 18.04 base image
      - image: 'cimg/base:2020.12-18.04'
    steps:
      - php/install-php:
          version: '8.0'
      # Minimal packages for symfony to run with xdebug
      - run: sudo apt install php8.0-xdebug php8.0-xml
      - checkout
      # Add xdebug.ini with xdebug.var_display_max_depth = -1
      - run: sudo cp ~/project/xdebug.ini /etc/php/7.4/mods-available/xdebug.ini
      - php/install-composer:
          install-version: 2.0.8
      # Try to limit memory to 128M and timeout after 30s so that cache:clear crashes more quickly
      # console cache:clear is run after install with the composer.json settings
      - run: timeout 30s php8.0 -d memory_limit=128M /usr/local/bin/composer install --no-interaction --prefer-dist
orbs:
  php: circleci/php@1.1.0
version: 2.1

workflows:
  install:
    jobs:
      - install_and_test_72
      - install_and_test_73
      - install_and_test_74
      - install_and_test_80



