jobs:
  install_and_test:
    docker:
      # Ubuntu 18.04 base image
      - image: 'cimg/base:2020.12-18.04'
    steps:
      - php/install-php:
          version: '7.2'
      # Minimal packages for symfony to run with xdebug
      - run: sudo apt install php7.2-xdebug php7.2-xml
      - checkout
      - run: sudo cp ~/project/xdebug.ini /etc/php/7.2/mods-available/xdebug.ini
      - php/install-composer:
          install-version: 2.0.8
      - run: sudo ln -s /usr/local/bin/composer /usr/bin/composer
      - run: lsb_release -a
      - run: php7.2 -d memory_limit=128M composer install --no-interaction --prefer-dist
orbs:
  php: circleci/php@1.1.0
version: 2.1

workflows:
  install:
    jobs:
      - install_and_test



